LIQUIDATION_SERVER_ENDPOINT = "http://localhost:9000/v1"
AUCTION_SERVER_ENDPOINT = "http://localhost:9000/bid"

LIQUIDATION_SERVER_ENDPOINT_GETOPPS = (
    f"{LIQUIDATION_SERVER_ENDPOINT}/liquidation/opportunities"
)
LIQUIDATION_SERVER_ENDPOINT_BID = f"{LIQUIDATION_SERVER_ENDPOINT}/liquidation/bid"
