[tool.poetry]
name = "block-watch"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
web3 = "^6.18.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
