packages:
  - "sdk/js"
  - "sdk/solidity"
  - "examples/easy_lend"
  - "scripts/dex-router"
  - "scripts/limonade"
  - "scripts/opportunity-provider"
  - "scripts/swap-beacon"
  - "apps/swap"
  - "scripts/rfq-stress-test"
  - "scripts/rfq-dynamic-deadline"

catalog:
  "typescript": 5.5.4
  "@coral-xyz/anchor": 0.31.0
  "@kamino-finance/limo-sdk": 1.0.8
  "@solana/web3.js": 1.95.3
  "@solana/spl-token": 0.4.9
  "viem": 2.16.2
  "@types/yargs": 17.0.32
  "@types/node": 20.14.9
  "yargs": 17.7.2
  "jest": 27.5.1
  "@coral-xyz/anchor-cli": 0.31.0
  "bs58": 6.0.0
  "ts-node": 10.9.1
