packages:
  - "sdk/js"
  - "sdk/solidity"
  - "examples/easy_lend"
  - "scripts/dex-router"
  - "scripts/limonade"
  - "scripts/opportunity-provider"
  - "scripts/opportunity-provider-limo"
  - "scripts/swap-beacon"

catalog:
  "typescript": 5.5.4
  "@coral-xyz/anchor": 0.30.1
  "@kamino-finance/limo-sdk": 0.7.1
  "@solana/web3.js": 1.95.3
  "viem": 2.16.2
  "@types/yargs": 17.0.32
  "@types/node": 20.14.9
  "yargs": 17.7.2
  "jest": 27.5.1
  "@coral-xyz/anchor-cli": 0.30.1
