[workspace]
members = [
    "testing",
    "programs/*",
    "cli"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]
anchor-lang = { git = "https://github.com/coral-xyz/anchor", rev = "6df05aa" }
anchor-spl = { git = "https://github.com/coral-xyz/anchor", rev = "6df05aa" }
anchor-client = { git = "https://github.com/coral-xyz/anchor", rev = "6df05aa" }
litesvm = { git = "https://github.com/LiteSVM/litesvm", rev = "5346e86" }
solana-program = "=2.1.0"
solana-program-test = "=2.1.0"
solana-sdk = "=2.1.0"
