BEACON_SERVER_ENDPOINT = "http://localhost:9000"
AUCTION_SERVER_ENDPOINT = f"http://localhost:9000/bid"

BEACON_SERVER_ENDPOINT_SURFACE = f"{BEACON_SERVER_ENDPOINT}/surface"
BEACON_SERVER_ENDPOINT_GETOPPS = f"{BEACON_SERVER_ENDPOINT}/getOpps"