apiVersion: apps/v1
kind: Deployment
metadata:
  name: per-server
spec:
  selector:
    matchLabels:
      app: per-server
  replicas: 1
  template:
    metadata:
      labels:
        app: per-server
    spec:
      containers:
        - name: anvil
          image: ghcr.io/foundry-rs/foundry:latest
          command:
            - /bin/sh
            - -c
            - "anvil --gas-limit 500000000000000000 --block-time 1"
        - name: auction-server
          image: server
          command:
            - /bin/sh
            - -c
            - "auction-server run"
          volumeMounts:
            - name: config-vol
              mountPath: /config
              readOnly: true
          env:
            # default first private key of anvil
            - name: PER_PRIVATE_KEY
              value: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
            - name: PER_CONFIG
              value: /config/config.yaml
      volumes:
        - name: config-vol
          configMap:
            name: auction-server-config
