/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Bid {
    BidEvm(models::BidEvm),
    BidSvm(models::BidSvm),
}

impl Default for Bid {
    fn default() -> Self {
        Self::BidEvm(Default::default())
    }
}
