/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BidCreateEvm {
    /// Amount of bid in wei.
    #[serde(rename = "amount")]
    pub amount:          String,
    /// The chain id to bid on.
    #[serde(rename = "chain_id")]
    pub chain_id:        String,
    /// The permission key to bid on.
    #[serde(rename = "permission_key")]
    pub permission_key:  String,
    /// Calldata for the contract call.
    #[serde(rename = "target_calldata")]
    pub target_calldata: String,
    /// The contract address to call.
    #[serde(rename = "target_contract")]
    pub target_contract: String,
}

impl BidCreateEvm {
    pub fn new(
        amount: String,
        chain_id: String,
        permission_key: String,
        target_calldata: String,
        target_contract: String,
    ) -> BidCreateEvm {
        BidCreateEvm {
            amount,
            chain_id,
            permission_key,
            target_calldata,
            target_contract,
        }
    }
}
