/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BidStatus {
    BidStatusEvm(models::BidStatusEvm),
    BidStatusSvm(models::BidStatusSvm),
}

impl Default for BidStatus {
    fn default() -> Self {
        Self::BidStatusEvm(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "won")]
    Won,
    #[serde(rename = "expired")]
    Expired,
}

impl Default for Type {
    fn default() -> Type {
        Self::Won
    }
}
