/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BidCreate {
    BidCreateEvm(models::BidCreateEvm),
    BidCreateSvm(models::BidCreateSvm),
}

impl Default for BidCreate {
    fn default() -> Self {
        Self::BidCreateEvm(Default::default())
    }
}
