/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum BidStatusEvm {
    #[serde(rename = "Pending")]
    Pending(models::Pending),
    #[serde(rename = "Submitted")]
    Submitted(models::Submitted),
    #[serde(rename = "Lost")]
    Lost(models::Lost),
    #[serde(rename = "Won")]
    Won(models::Won),
}

impl Default for BidStatusEvm {
    fn default() -> Self {
        Self::Pending(Default::default())
    }
}
