/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BidCreateSvm {
    /// The chain id to bid on.
    #[serde(rename = "chain_id")]
    pub chain_id:    String,
    /// The transaction for bid.
    #[serde(rename = "transaction")]
    pub transaction: String,
}

impl BidCreateSvm {
    pub fn new(chain_id: String, transaction: String) -> BidCreateSvm {
        BidCreateSvm {
            chain_id,
            transaction,
        }
    }
}
