/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bids {
    #[serde(rename = "items")]
    pub items: Vec<models::Bid>,
}

impl Bids {
    pub fn new(items: Vec<models::Bid>) -> Bids {
        Bids { items }
    }
}
