/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientMessageOneOfParams {
    #[serde(rename = "chain_ids")]
    pub chain_ids: Vec<String>,
}

impl ClientMessageOneOfParams {
    pub fn new(chain_ids: Vec<String>) -> ClientMessageOneOfParams {
        ClientMessageOneOfParams { chain_ids }
    }
}
