/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientMessageOneOf3Params {
    #[serde(rename = "opportunity_bid")]
    pub opportunity_bid: models::OpportunityBidEvm,
    #[serde(rename = "opportunity_id")]
    pub opportunity_id:  String,
}

impl ClientMessageOneOf3Params {
    pub fn new(
        opportunity_bid: models::OpportunityBidEvm,
        opportunity_id: String,
    ) -> ClientMessageOneOf3Params {
        ClientMessageOneOf3Params {
            opportunity_bid,
            opportunity_id,
        }
    }
}
