/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientMessageOneOf2Params {
    #[serde(rename = "bid")]
    pub bid: models::BidCreate,
}

impl ClientMessageOneOf2Params {
    pub fn new(bid: models::BidCreate) -> ClientMessageOneOf2Params {
        ClientMessageOneOf2Params { bid }
    }
}
