/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientMessageOneOf2 {
    #[serde(rename = "method")]
    pub method: Method,
    #[serde(rename = "params")]
    pub params: models::ClientMessageOneOf2Params,
}

impl ClientMessageOneOf2 {
    pub fn new(method: Method, params: models::ClientMessageOneOf2Params) -> ClientMessageOneOf2 {
        ClientMessageOneOf2 { method, params }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "post_bid")]
    PostBid,
}

impl Default for Method {
    fn default() -> Method {
        Self::PostBid
    }
}
