/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientRequest {
    #[serde(rename = "method")]
    pub method: Method,
    #[serde(rename = "params")]
    pub params: models::ClientMessageOneOf3Params,
    #[serde(rename = "id")]
    pub id:     String,
}

impl ClientRequest {
    pub fn new(
        method: Method,
        params: models::ClientMessageOneOf3Params,
        id: String,
    ) -> ClientRequest {
        ClientRequest { method, params, id }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "post_opportunity_bid")]
    PostOpportunityBid,
}

impl Default for Method {
    fn default() -> Method {
        Self::PostOpportunityBid
    }
}
