/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ClientMessage {
    #[serde(rename = "ClientMessage_oneOf")]
    ClientMessageOneOf(models::ClientMessageOneOf),
    #[serde(rename = "ClientMessage_oneOf_1")]
    ClientMessageOneOf1(models::ClientMessageOneOf1),
    #[serde(rename = "ClientMessage_oneOf_2")]
    ClientMessageOneOf2(models::ClientMessageOneOf2),
    #[serde(rename = "ClientMessage_oneOf_3")]
    ClientMessageOneOf3(models::ClientMessageOneOf3),
}

impl Default for ClientMessage {
    fn default() -> Self {
        Self::ClientMessageOneOf(Default::default())
    }
}
