/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

/// Failed : The bid was submitted on-chain, was included in a block, but resulted in a failed transaction.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Failed {
    #[serde(rename = "result")]
    pub result: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl Failed {
    /// The bid was submitted on-chain, was included in a block, but resulted in a failed transaction.
    pub fn new(result: String, r#type: Type) -> Failed {
        Failed { result, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Type {
    fn default() -> Type {
        Self::Failed
    }
}
