/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBidsByTimeDeprecated400Response {
    #[serde(rename = "error")]
    pub error: String,
}

impl GetBidsByTimeDeprecated400Response {
    pub fn new(error: String) -> GetBidsByTimeDeprecated400Response {
        GetBidsByTimeDeprecated400Response { error }
    }
}
