/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

/// OpportunityDeleteV1Svm : Opportunity parameters needed for deleting live opportunities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpportunityDeleteV1Svm {
    /// The chain id for the opportunity.
    #[serde(rename = "chain_id")]
    pub chain_id:           String,
    /// The permission account for the opportunity.
    #[serde(rename = "permission_account")]
    pub permission_account: String,
    #[serde(rename = "program")]
    pub program:            models::ProgramSvm,
    /// The router account for the opportunity.
    #[serde(rename = "router")]
    pub router:             String,
}

impl OpportunityDeleteV1Svm {
    /// Opportunity parameters needed for deleting live opportunities.
    pub fn new(
        chain_id: String,
        permission_account: String,
        program: models::ProgramSvm,
        router: String,
    ) -> OpportunityDeleteV1Svm {
        OpportunityDeleteV1Svm {
            chain_id,
            permission_account,
            program,
            router,
        }
    }
}
