/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

/// OpportunityCreateProgramParamsV1Svm : Program specific parameters for the opportunity.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "program")]
pub enum OpportunityCreateProgramParamsV1Svm {
    #[serde(rename = "limo")]
    Limo(models::Limo),
    #[serde(rename = "phantom")]
    Phantom(models::Phantom),
}

impl Default for OpportunityCreateProgramParamsV1Svm {
    fn default() -> Self {
        Self::Limo(Default::default())
    }
}
