/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

/// OpportunityDeleteV1Evm : Opportunity parameters needed for deleting live opportunities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpportunityDeleteV1Evm {
    /// The chain id for the opportunity.
    #[serde(rename = "chain_id")]
    pub chain_id:       String,
    /// The permission key of the opportunity.
    #[serde(rename = "permission_key")]
    pub permission_key: String,
}

impl OpportunityDeleteV1Evm {
    /// Opportunity parameters needed for deleting live opportunities.
    pub fn new(chain_id: String, permission_key: String) -> OpportunityDeleteV1Evm {
        OpportunityDeleteV1Evm {
            chain_id,
            permission_key,
        }
    }
}
