/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpportunityBidEvm {
    /// The bid amount in wei.
    #[serde(rename = "amount")]
    pub amount:         String,
    /// The latest unix timestamp in seconds until which the bid is valid.
    #[serde(rename = "deadline")]
    pub deadline:       String,
    /// The executor address.
    #[serde(rename = "executor")]
    pub executor:       String,
    /// The nonce of the bid permit signature.
    #[serde(rename = "nonce")]
    pub nonce:          String,
    /// The opportunity permission key.
    #[serde(rename = "permission_key")]
    pub permission_key: String,
    #[serde(rename = "signature")]
    pub signature:      String,
}

impl OpportunityBidEvm {
    pub fn new(
        amount: String,
        deadline: String,
        executor: String,
        nonce: String,
        permission_key: String,
        signature: String,
    ) -> OpportunityBidEvm {
        OpportunityBidEvm {
            amount,
            deadline,
            executor,
            nonce,
            permission_key,
            signature,
        }
    }
}
