/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpportunitySvm {
    /// The Limo order to be executed, encoded in base64.
    #[serde(rename = "order")]
    pub order:                       String,
    /// Address of the order account.
    #[serde(rename = "order_address")]
    pub order_address:               String,
    #[serde(rename = "program")]
    pub program:                     Program,
    #[serde(rename = "buy_token")]
    pub buy_token:                   models::TokenAmountSvm,
    /// The maximum slippage percentage that the user is willing to accept.
    #[serde(rename = "maximum_slippage_percentage")]
    pub maximum_slippage_percentage: f64,
    /// The permission account to be permitted by the ER contract for the opportunity execution of the protocol.
    #[serde(rename = "permission_account")]
    pub permission_account:          String,
    /// The router account to be used for the opportunity execution of the protocol.
    #[serde(rename = "router_account")]
    pub router_account:              String,
    #[serde(rename = "sell_token")]
    pub sell_token:                  models::TokenAmountSvm,
    /// The user wallet address which requested the quote from the wallet.
    #[serde(rename = "user_wallet_address")]
    pub user_wallet_address:         String,
    #[serde(rename = "chain_id")]
    pub chain_id:                    String,
    #[serde(rename = "version")]
    pub version:                     Version,
    /// Creation time of the opportunity (in microseconds since the Unix epoch).
    #[serde(rename = "creation_time")]
    pub creation_time:               i32,
    /// The opportunity unique id.
    #[serde(rename = "opportunity_id")]
    pub opportunity_id:              String,
    /// The slot where the program params were fetched from using the RPC.
    #[serde(rename = "slot")]
    pub slot:                        i64,
}

impl OpportunitySvm {
    pub fn new(
        order: String,
        order_address: String,
        program: Program,
        buy_token: models::TokenAmountSvm,
        maximum_slippage_percentage: f64,
        permission_account: String,
        router_account: String,
        sell_token: models::TokenAmountSvm,
        user_wallet_address: String,
        chain_id: String,
        version: Version,
        creation_time: i32,
        opportunity_id: String,
        slot: i64,
    ) -> OpportunitySvm {
        OpportunitySvm {
            order,
            order_address,
            program,
            buy_token,
            maximum_slippage_percentage,
            permission_account,
            router_account,
            sell_token,
            user_wallet_address,
            chain_id,
            version,
            creation_time,
            opportunity_id,
            slot,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Program {
    #[serde(rename = "phantom")]
    Phantom,
}

impl Default for Program {
    fn default() -> Program {
        Self::Phantom
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "v1")]
    V1,
}

impl Default for Version {
    fn default() -> Version {
        Self::V1
    }
}
