/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

/// OpportunityDelete : The input type for deleting opportunities.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "chain_type")]
pub enum OpportunityDelete {
    #[serde(rename = "svm")]
    Svm(models::Svm),
    #[serde(rename = "evm")]
    Evm(models::Evm),
}

impl Default for OpportunityDelete {
    fn default() -> Self {
        Self::Svm(Default::default())
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "v1")]
    V1,
}

impl Default for Version {
    fn default() -> Version {
        Self::V1
    }
}
