/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProgramSvm {
    #[serde(rename = "phantom")]
    Phantom,
    #[serde(rename = "limo")]
    Limo,
}

impl std::fmt::Display for ProgramSvm {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Phantom => write!(f, "phantom"),
            Self::Limo => write!(f, "limo"),
        }
    }
}

impl Default for ProgramSvm {
    fn default() -> ProgramSvm {
        Self::Phantom
    }
}
