/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "program")]
pub enum QuoteCreateV1Svm {
    #[serde(rename = "phantom_1")]
    Phantom1(models::Phantom1),
}

impl Default for QuoteCreateV1Svm {
    fn default() -> Self {
        Self::Phantom1(Default::default())
    }
}
