/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerUpdateResponseOneOf1 {
    #[serde(rename = "status")]
    pub status: models::BidStatusWithId,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ServerUpdateResponseOneOf1 {
    pub fn new(status: models::BidStatusWithId, r#type: Type) -> ServerUpdateResponseOneOf1 {
        ServerUpdateResponseOneOf1 { status, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "bid_status_update")]
    BidStatusUpdate,
}

impl Default for Type {
    fn default() -> Type {
        Self::BidStatusUpdate
    }
}
