/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerUpdateResponseOneOf2 {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "update")]
    pub update: models::SvmChainUpdate,
}

impl ServerUpdateResponseOneOf2 {
    pub fn new(r#type: Type, update: models::SvmChainUpdate) -> ServerUpdateResponseOneOf2 {
        ServerUpdateResponseOneOf2 { r#type, update }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "svm_chain_update")]
    SvmChainUpdate,
}

impl Default for Type {
    fn default() -> Type {
        Self::SvmChainUpdate
    }
}
