/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerUpdateResponseOneOf {
    #[serde(rename = "opportunity")]
    pub opportunity: models::Opportunity,
    #[serde(rename = "type")]
    pub r#type:      Type,
}

impl ServerUpdateResponseOneOf {
    pub fn new(opportunity: models::Opportunity, r#type: Type) -> ServerUpdateResponseOneOf {
        ServerUpdateResponseOneOf {
            opportunity,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "new_opportunity")]
    NewOpportunity,
}

impl Default for Type {
    fn default() -> Type {
        Self::NewOpportunity
    }
}
