/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

/// ServerUpdateResponse : This enum is used to send an update to the client for any subscriptions made.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ServerUpdateResponse {
    #[serde(rename = "ServerUpdateResponse_oneOf")]
    ServerUpdateResponseOneOf(models::ServerUpdateResponseOneOf),
    #[serde(rename = "ServerUpdateResponse_oneOf_1")]
    ServerUpdateResponseOneOf1(models::ServerUpdateResponseOneOf1),
    #[serde(rename = "ServerUpdateResponse_oneOf_2")]
    ServerUpdateResponseOneOf2(models::ServerUpdateResponseOneOf2),
    #[serde(rename = "ServerUpdateResponse_oneOf_3")]
    ServerUpdateResponseOneOf3(models::ServerUpdateResponseOneOf3),
}

impl Default for ServerUpdateResponse {
    fn default() -> Self {
        Self::ServerUpdateResponseOneOf(Default::default())
    }
}
