/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerUpdateResponseOneOf3 {
    #[serde(rename = "opportunity_delete")]
    pub opportunity_delete: models::OpportunityDelete,
    #[serde(rename = "type")]
    pub r#type:             Type,
}

impl ServerUpdateResponseOneOf3 {
    pub fn new(
        opportunity_delete: models::OpportunityDelete,
        r#type: Type,
    ) -> ServerUpdateResponseOneOf3 {
        ServerUpdateResponseOneOf3 {
            opportunity_delete,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "remove_opportunities")]
    RemoveOpportunities,
}

impl Default for Type {
    fn default() -> Type {
        Self::RemoveOpportunities
    }
}
