/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SvmChainUpdate {
    #[serde(rename = "blockhash")]
    pub blockhash:                 String,
    #[serde(rename = "chain_id")]
    pub chain_id:                  String,
    /// The prioritization fee that the server suggests to use for the next transaction
    #[serde(rename = "latest_prioritization_fee")]
    pub latest_prioritization_fee: i64,
}

impl SvmChainUpdate {
    pub fn new(
        blockhash: String,
        chain_id: String,
        latest_prioritization_fee: i64,
    ) -> SvmChainUpdate {
        SvmChainUpdate {
            blockhash,
            chain_id,
            latest_prioritization_fee,
        }
    }
}
