/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenAmountSvm {
    /// The token amount in lamports.
    #[serde(rename = "amount")]
    pub amount: i64,
    /// The token contract address.
    #[serde(rename = "token")]
    pub token:  String,
}

impl TokenAmountSvm {
    pub fn new(amount: i64, token: String) -> TokenAmountSvm {
        TokenAmountSvm { amount, token }
    }
}
