/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenAmountEvm {
    /// The token amount.
    #[serde(rename = "amount")]
    pub amount: String,
    /// The token contract address.
    #[serde(rename = "token")]
    pub token:  String,
}

impl TokenAmountEvm {
    pub fn new(amount: String, token: String) -> TokenAmountEvm {
        TokenAmountEvm { amount, token }
    }
}
