/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V12 {
    /// The chain id for the opportunity.
    #[serde(rename = "chain_id")]
    pub chain_id:       String,
    /// The permission key of the opportunity.
    #[serde(rename = "permission_key")]
    pub permission_key: String,
    #[serde(rename = "version")]
    pub version:        Version,
}

impl V12 {
    pub fn new(chain_id: String, permission_key: String, version: Version) -> V12 {
        V12 {
            chain_id,
            permission_key,
            version,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "v1")]
    V1,
}

impl Default for Version {
    fn default() -> Version {
        Self::V1
    }
}
