/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V13 {
    /// The chain id for the opportunity.
    #[serde(rename = "chain_id")]
    pub chain_id:           String,
    /// The permission account for the opportunity.
    #[serde(rename = "permission_account")]
    pub permission_account: String,
    #[serde(rename = "program")]
    pub program:            models::ProgramSvm,
    /// The router account for the opportunity.
    #[serde(rename = "router")]
    pub router:             String,
    #[serde(rename = "version")]
    pub version:            Version,
}

impl V13 {
    pub fn new(
        chain_id: String,
        permission_account: String,
        program: models::ProgramSvm,
        router: String,
        version: Version,
    ) -> V13 {
        V13 {
            chain_id,
            permission_account,
            program,
            router,
            version,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "v1")]
    V1,
}

impl Default for Version {
    fn default() -> Version {
        Self::V1
    }
}
