/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

/// Won : The bid won the auction, which is concluded with the transaction with the given hash and index.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Won {
    #[serde(rename = "index")]
    pub index:  i32,
    #[serde(rename = "result")]
    pub result: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl Won {
    /// The bid won the auction, which is concluded with the transaction with the given hash and index.
    pub fn new(index: i32, result: String, r#type: Type) -> Won {
        Won {
            index,
            result,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "won")]
    Won,
}

impl Default for Type {
    fn default() -> Type {
        Self::Won
    }
}
