/*
 * auction-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.14.0
 *
 * Generated by: https://openapi-generator.tech
 */

use {
    crate::models,
    serde::{
        Deserialize,
        Serialize,
    },
};

/// Won1 : The bid won the auction and was included in a block successfully.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Won1 {
    #[serde(rename = "result")]
    pub result: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl Won1 {
    /// The bid won the auction and was included in a block successfully.
    pub fn new(result: String, r#type: Type) -> Won1 {
        Won1 { result, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "won")]
    Won,
}

impl Default for Type {
    fn default() -> Type {
        Self::Won
    }
}
