name: Publish Express Relay SVM to crates.io

on:
  push:
    branches:
      - fix_express_relay_cargo_workflow
jobs:
  publish-express-relay-svm:
    name: Publish Express Relay SVM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - run: cargo publish --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        working-directory: "contracts/svm/programs/express_relay"
