name: Publish Express Relay SVM to crates.io

on:
  push:
    tags:
      - express-relay-svm-v*
jobs:
  publish-express-relay-svm:
    name: Publish Express Relay SVM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - run: cargo publish --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.PYTH_NETWORK_PYTH_OPS_CARGO_PUSH }}
        working-directory: "contracts/svm/programs/express_relay"
