name: Publish Express Relay API Types to crates.io

on:
  push:
    tags:
      - express-relay-api-types-v*
jobs:
  publish-express-relay-api-types:
    name: Publish Express Relay API Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - run: cargo publish -p express-relay-api-types --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.PYTH_NETWORK_PYTH_OPS_CARGO_PUSH }}
