name: Build and Push Rust Services Image
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      dispatch_description:
        description: "Dispatch description"
        required: true
        type: string
permissions:
  contents: read
  id-token: write
  packages: write
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  server-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set image tag to version of the git tag
        if: ${{ startsWith(github.ref, 'refs/tags/server-v') }}
        run: |
          PREFIX="refs/tags/server-"
          VERSION="${GITHUB_REF:${#PREFIX}}"
          echo "IMAGE_TAG=${VERSION}" >> "${GITHUB_ENV}"
      - name: Set image tag to the git commit hash
        if: ${{ !startsWith(github.ref, 'refs/tags/server-v') }}
        run: |
          echo "IMAGE_TAG=${{ github.sha }}" >> "${GITHUB_ENV}"
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta_server
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta_monitor
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-monitor
      - name: Build and push server docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta_server.outputs.tags }}
          labels: ${{ steps.meta_server.outputs.labels }}
      - name: Build and push vault monitor docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./per_sdk/Dockerfile
          push: true
          tags: ${{ steps.meta_monitor.outputs.tags }}
          labels: ${{ steps.meta_monitor.outputs.labels }}
