name: Release SVM Program

on:
  push:
    branches:
      - main
    paths:
      - contracts/svm/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Solana Verify CLI
        run: |
          cargo install solana-verify --git https://github.com/Ellipsis-Labs/solana-verifiable-build --rev 121568e
      - name: Build
        working-directory: ./contracts/svm
        run: solana-verify build
      - name: Print Hash
        working-directory: ./contracts/svm
        run: sha256sum ./target/deploy/express_relay.so
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: express_relay.so
          path: ./contracts/svm/target/deploy/express_relay.so
          retention-days: 90
