name: Test SVM contracts

on:
  pull_request:
    paths:
      - contracts/svm/**
  push:
    branches:
      - main
    paths:
      - contracts/svm/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts/svm
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true
      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.26/install)"
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Build
        run: cargo-build-sbf
      - name: Run tests
        run: cargo-test-sbf && cargo test -p testing
