chains:
  development:
    geth_rpc_addr: http://localhost:8545
    geth_ws_addr: ws://127.0.0.1:9545
    rpc_timeout: 5
    express_relay_contract: 0xa513E6E4b8f2a923D98304ec87F64353C4D5C853
    adapter_factory_contract: 0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e
    legacy_tx: false
    poll_interval: 1
    subwallets:
      - 0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
      - 0xdecafdecafdecafdecafdecafdecafdecafdecaf
  development-solana:
    express_relay_program_id: PytERJFhAKuNNuaiXkApLfWzwNwSNDACpigT3LwQfou
    rpc_read_url: http://localhost:8899
    rpc_tx_submission_urls:
      - http://localhost:8899
    ws_addr: ws://localhost:8900
    accepted_token_programs:
      - TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
      - TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
    ordered_fee_tokens:
      - EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
      - Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
      - So11111111111111111111111111111111111111112
    token_whitelist:
      enabled: true
      whitelist_mints:
        - Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
        - So11111111111111111111111111111111111111112
        - EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
    allow_permissionless_quote_requests: true
    minimum_fee_list:
      profiles:
        - profile_id: 0b059fa2-189f-4498-a646-e7ee1ed79c3c
          minimum_fees:
            - mint: Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
              fee_ppm: 100
            - mint: So11111111111111111111111111111111111111112
              fee_ppm: 200

lazer:
  price_feeds:
    - id: 7
      mint: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
      exponent: -8
    - id: 397
      mint: cbbtcf3aa214zXHbiAZQwf4122FBYbraNdFqgw4iMij
      exponent: -8
