chains:
  development-solana:
    express_relay_program_id: PytERJFhAKuNNuaiXkApLfWzwNwSNDACpigT3LwQfou
    rpc_read_url: http://localhost:8899
    rpc_tx_submission_urls:
      - http://localhost:8899
    ws_addr: ws://localhost:8900
    accepted_token_programs:
      - TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
      - TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
    ordered_fee_tokens:
      - EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
      - Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
      - So11111111111111111111111111111111111111112
    jupiter_ultra_url: https://ultra-api.jup.ag
